/** Align with Phase 5C: only available + stock > 0 is customer-available PIN stock. */
export const STOCK_STATUSES = [
  "available",
  "out_of_stock",
  "booked",
  "transit",
  "upcoming",
  "delivered",
] as const;

export type StockStatus = (typeof STOCK_STATUSES)[number];

export const MAX_BULK_ROWS = 500;
/** OEM sheets (e.g. Volvo workbooks) often exceed 2MB with formatting. */
export const MAX_BULK_FILE_BYTES = 12 * 1024 * 1024;
export const LOW_STOCK_THRESHOLD = 2;

export const FORBIDDEN_IMPORT_COLUMNS = new Set([
  "dealerid",
  "dealer_id",
  "organizationid",
  "organization_id",
  "userid",
  "user_id",
  "ownerid",
  "owner_id",
  "createdby",
  "created_by",
  "verification",
  "verificationstatus",
  "oemauthorization",
  "billingstatus",
  "entitlements",
]);

/**
 * Header aliases after normalizeHeader (trim, lower, spaces/hyphens → underscore).
 * New-car real listing fields (mileage, CC, power, etc.) map into metadata.specifications.
 */
export const IMPORT_HEADER_ALIASES: Record<string, string> = {
  brand: "brand",
  make: "brand",
  manufacturer: "brand",
  oem: "brand",
  car_make: "brand",
  vehicle_make: "brand",
  vehicle_brand: "brand",
  company: "brand",
  model: "model",
  car_model: "model",
  vehicle_model: "model",
  model_name: "model",
  vehicle_name: "vehicle_name",
  car_name: "model",
  series: "model",
  carline: "model",
  nameplate: "model",
  vehicle: "vehicle_name",
  car: "vehicle_name",
  variant: "variant",
  trim: "variant",
  variant_name: "variant",
  grade: "variant",
  derivative: "variant",
  model_year: "year",
  year: "year",
  mfg_year: "year",
  manufacturing_year: "year",
  fuel: "fuel_type",
  fuel_type: "fuel_type",
  fuel_type_name: "fuel_type",
  transmission: "transmission",
  gearbox: "transmission",
  colour: "colour",
  color: "colour",
  colors: "colour",
  exterior_color: "colour",
  exterior_colour: "colour",
  stock: "stock",
  qty: "stock",
  quantity: "stock",
  available_stock: "stock",
  units: "stock",
  stock_status: "stock_status",
  status: "stock_status",
  availability_status: "stock_status",
  inventory_status: "stock_status",
  ex_showroom_price: "ex_showroom_price",
  ex_showroom: "ex_showroom_price",
  exshowroom_price: "ex_showroom_price",
  exshowroom: "ex_showroom_price",
  ex_showroom_inr: "ex_showroom_price",
  dealer_price: "dealer_price",
  selling_price: "dealer_price",
  offer_price: "dealer_price",
  price: "price",
  on_road_price: "on_road_price",
  onroad_price: "on_road_price",
  on_road: "on_road_price",
  discount: "discount",
  discount_amount: "discount",
  branch: "branch",
  branch_name: "branch",
  showroom: "branch",
  location: "branch",
  branch_id: "branch_id",
  pincode: "pincode",
  pin: "pincode",
  pin_code: "pincode",
  postal_code: "pincode",
  zip: "pincode",
  internal_reference: "internal_reference",
  reference: "internal_reference",
  ref: "internal_reference",
  sku: "internal_reference",
  vin: "internal_reference",
  expected_availability: "expected_availability",
  availability: "expected_availability",
  image_url: "image_url",
  image: "image_url",
  main_image_url: "image_url",
  photo: "image_url",
  notes: "notes",
  description: "notes",
  remarks: "notes",
  km_driven: "km_driven",
  kms: "km_driven",
  kilometers: "km_driven",
  ownership: "ownership",
  owners: "ownership",
  registration_state: "registration_state",
  reg_state: "registration_state",
  // Real new-car spec columns (optional — stored in metadata.specifications)
  body_type: "body_type",
  body: "body_type",
  engine_cc: "engine_cc",
  cc: "engine_cc",
  engine: "engine_cc",
  engine_capacity: "engine_cc",
  mileage: "mileage",
  mileage_kmpl: "mileage",
  arai_mileage: "mileage",
  range_km: "range_km",
  range: "range_km",
  ev_range: "range_km",
  claimed_range: "range_km",
  battery_kwh: "battery_kwh",
  battery: "battery_kwh",
  battery_capacity: "battery_kwh",
  battery_pack: "battery_kwh",
  power: "power",
  bhp: "power",
  max_power: "power",
  torque: "torque",
  nm: "torque",
  max_torque: "torque",
  seating: "seating",
  seating_capacity: "seating",
  seats: "seating",
  boot_space: "boot_space",
  boot: "boot_space",
  boot_space_litres: "boot_space",
  ground_clearance: "ground_clearance",
  ground_clearance_mm: "ground_clearance",
  drive_type: "drive_type",
  drivetrain: "drive_type",
  airbags: "airbags",
  safety_airbags: "airbags",
  waiting_period_days: "waiting_period_days",
  waiting_period: "waiting_period_days",
  brochure_url: "brochure_url",
  brochure: "brochure_url",
  features: "features",
  key_features: "features",
};
