-- Lender catalogue from published rate cards (Sept 2026). Existing slugs are left untouched.
INSERT INTO "banks" ("id", "name", "slug", "logo_url", "bank_type", "interest_rate_min", "interest_rate_max", "max_tenure_months", "processing_fee", "max_loan_amount", "features", "is_active", "is_featured", "ranking_score", "min_cibil", "short_code", "created_at", "updated_at")
VALUES
  (gen_random_uuid()::text, 'State Bank of India', 'sbi', '/partners/banks/sbi.svg', 'bank', 8.9, 9.85, 84, '₹500 – ₹2,000', 10000000, '["CIBIL-linked pricing","No prepayment penalty on floating"]'::jsonb, true, true, 92, 650, 'SBI', NOW(), NOW()),
  (gen_random_uuid()::text, 'Bank of Baroda', 'bob', '/partners/banks/bob.svg', 'bank', 7.6, 11.35, 84, 'Up to ₹2,000', 10000000, '["Floating rates from 7.60%","Nil fee for women borrowers"]'::jsonb, true, true, 88, 680, 'BOB', NOW(), NOW()),
  (gen_random_uuid()::text, 'Canara Bank', 'canara', '/partners/banks/canara.svg', 'bank', 7.45, 11.45, 84, '0.25% (₹1,000 – ₹5,000)', 10000000, '["Lowest PSU starting rate"]'::jsonb, true, false, 85, 680, 'CANARA', NOW(), NOW()),
  (gen_random_uuid()::text, 'Union Bank of India', 'union', '/partners/banks/union.svg', 'bank', 7.5, 10, 84, 'Up to ₹1,000', 10000000, '["Low processing fee"]'::jsonb, true, false, 82, 680, 'UNION', NOW(), NOW()),
  (gen_random_uuid()::text, 'Punjab National Bank', 'pnb', '/partners/banks/pnb.svg', 'bank', 7.6, 10.7, 84, '0.25% (₹1,000 – ₹1,500)', 10000000, '["Floating from 7.60%","Special rates for govt employees"]'::jsonb, true, true, 84, 680, 'PNB', NOW(), NOW()),
  (gen_random_uuid()::text, 'Bank of India', 'boi', '/partners/banks/boi.svg', 'bank', 7.6, 12.55, 84, '0.25% (₹2,500 – ₹10,000)', 5000000, '["No prepayment penalty","50% fee waiver on EVs"]'::jsonb, true, false, 80, 670, 'BOI', NOW(), NOW()),
  (gen_random_uuid()::text, 'Indian Overseas Bank', 'iob', '/partners/banks/iob.svg', 'bank', 7.55, 12, 84, 'Nil', 5000000, '["Nil processing fee"]'::jsonb, true, false, 74, 650, 'IOB', NOW(), NOW()),
  (gen_random_uuid()::text, 'UCO Bank', 'uco', '/partners/banks/uco.svg', 'bank', 7.35, 10, 84, '0.5% (max ₹5,000)', 5000000, '["Lowest published floor rate"]'::jsonb, true, false, 72, 650, 'UCO', NOW(), NOW()),
  (gen_random_uuid()::text, 'HDFC Bank', 'hdfc-bank', '/partners/banks/hdfcbank.svg', 'bank', 8.15, 12.5, 84, 'Up to ₹5,000', 25000000, '["Fast digital disbursal","Deep OEM tie-ups"]'::jsonb, true, true, 96, 700, 'HDFC', NOW(), NOW()),
  (gen_random_uuid()::text, 'ICICI Bank', 'icici-bank', '/partners/banks/icicibank.svg', 'bank', 8.35, 13, 84, 'Up to ₹5,000', 15000000, '["Pre-approved offers","Used car loans up to 100% value"]'::jsonb, true, true, 94, 700, 'ICICI', NOW(), NOW()),
  (gen_random_uuid()::text, 'Axis Bank', 'axis-bank', '/partners/banks/axisbank.svg', 'bank', 8.95, 13.5, 84, '1% (₹3,500 – ₹7,000)', 10000000, '["Maruti & OEM tie-up pricing"]'::jsonb, true, true, 90, 700, 'AXIS', NOW(), NOW()),
  (gen_random_uuid()::text, 'Kotak Mahindra Bank', 'kotak', '/partners/banks/kotak.svg', 'bank', 9, 13, 84, 'Nil – ₹5,000', 10000000, '["Festive fee waivers","Digital KYC"]'::jsonb, true, true, 88, 700, 'KOTAK', NOW(), NOW()),
  (gen_random_uuid()::text, 'IndusInd Bank', 'indusind', '/partners/banks/indusind.svg', 'bank', 8, 13, 84, 'Up to 1%', 10000000, '["Used & commercial specialist"]'::jsonb, true, false, 82, 680, 'INDUS', NOW(), NOW()),
  (gen_random_uuid()::text, 'IDFC FIRST Bank', 'idfc', '/partners/banks/idfc.svg', 'bank', 9, 14, 84, 'Up to 1%', 7500000, '["Flexible used-car & bike loans"]'::jsonb, true, false, 80, 680, 'IDFC', NOW(), NOW()),
  (gen_random_uuid()::text, 'AU Small Finance Bank', 'au-bank', '/partners/banks/au.svg', 'bank', 9.5, 14, 84, 'Up to 1.5%', 5000000, '["Self-employed friendly","Tier-2/3 reach"]'::jsonb, true, false, 76, 650, 'AU', NOW(), NOW()),
  (gen_random_uuid()::text, 'Tata Capital', 'tata-capital', '/partners/banks/tata-capital.svg', 'nbfc', 8.75, 14, 84, 'Up to 2%', 5000000, '["Used & commercial vehicles","Quick disbursal"]'::jsonb, true, true, 86, 650, 'TATA', NOW(), NOW()),
  (gen_random_uuid()::text, 'Cholamandalam Finance', 'cholamandalam', '/partners/banks/chola.svg', 'nbfc', 9.5, 15, 84, 'Up to 1.5%', 5000000, '["Older vehicles financed","Tier-3 coverage"]'::jsonb, true, true, 84, 620, 'CHOLA', NOW(), NOW()),
  (gen_random_uuid()::text, 'Mahindra Finance', 'mahindra-finance', '/partners/banks/mahindra-finance.svg', 'nbfc', 9.5, 16, 84, 'Up to 1.5%', 5000000, '["Rural & semi-urban","Tractor & CV loans"]'::jsonb, true, true, 82, 600, 'M&M', NOW(), NOW()),
  (gen_random_uuid()::text, 'Bajaj Finance', 'bajaj', '/partners/banks/bajaj.svg', 'nbfc', 12, 24, 48, 'Up to 2%', 2000000, '["Instant two-wheeler approvals"]'::jsonb, true, false, 78, 650, 'BAJAJ', NOW(), NOW())
ON CONFLICT ("slug") DO NOTHING;
