/** Canonical Excel/CSV column headers for bulk inventory upload (new + used + EV). */
export const INVENTORY_COLUMNS = [
  "Brand",
  "Model",
  "Variant",
  "Year",
  "Fuel",
  "Transmission",
  "Body Type",
  "Engine CC",
  "Mileage",
  "Range Km",
  "Battery kWh",
  "Power",
  "Torque",
  "Seating",
  "Boot Space",
  "Ground Clearance",
  "Drive Type",
  "Airbags",
  "KM Driven",
  "Ownership",
  "Price",
  "Ex-Showroom Price",
  "On-Road Price",
  "Color",
  "Registration State",
  "Description",
  "Dealer Price",
  "Discount",
  "Waiting Period Days",
  "Brochure URL",
  "Features",
  "Main Image URL",
  "Image URL 2",
  "Image URL 3",
  "Image URL 4",
] as const;

export type InventoryColumn = (typeof INVENTORY_COLUMNS)[number];

/** Header aliases (case-insensitive) → canonical column */
export const COLUMN_ALIASES: Record<string, InventoryColumn> = {
  brand: "Brand",
  model: "Model",
  variant: "Variant",
  year: "Year",
  fuel: "Fuel",
  "fuel type": "Fuel",
  transmission: "Transmission",
  "body type": "Body Type",
  body: "Body Type",
  "engine cc": "Engine CC",
  cc: "Engine CC",
  engine: "Engine CC",
  "engine capacity": "Engine CC",
  mileage: "Mileage",
  "mileage kmpl": "Mileage",
  "arai mileage": "Mileage",
  "range km": "Range Km",
  range: "Range Km",
  "ev range": "Range Km",
  "claimed range": "Range Km",
  "battery kwh": "Battery kWh",
  battery: "Battery kWh",
  "battery capacity": "Battery kWh",
  "battery pack": "Battery kWh",
  power: "Power",
  bhp: "Power",
  "max power": "Power",
  torque: "Torque",
  nm: "Torque",
  seating: "Seating",
  seats: "Seating",
  "seating capacity": "Seating",
  "boot space": "Boot Space",
  boot: "Boot Space",
  "ground clearance": "Ground Clearance",
  "drive type": "Drive Type",
  drivetrain: "Drive Type",
  airbags: "Airbags",
  "km driven": "KM Driven",
  kms: "KM Driven",
  kilometers: "KM Driven",
  ownership: "Ownership",
  owners: "Ownership",
  price: "Price",
  "selling price": "Price",
  "ex showroom price": "Ex-Showroom Price",
  "ex-showroom price": "Ex-Showroom Price",
  exshowroom: "Ex-Showroom Price",
  "on road price": "On-Road Price",
  "on-road price": "On-Road Price",
  onroad: "On-Road Price",
  color: "Color",
  "registration state": "Registration State",
  state: "Registration State",
  description: "Description",
  "dealer price": "Dealer Price",
  discount: "Discount",
  "waiting period days": "Waiting Period Days",
  "waiting period": "Waiting Period Days",
  "brochure url": "Brochure URL",
  brochure: "Brochure URL",
  features: "Features",
  "key features": "Features",
  "main image url": "Main Image URL",
  image: "Main Image URL",
  "image url": "Main Image URL",
  "image url 1": "Main Image URL",
  "image 1": "Main Image URL",
  "image url 2": "Image URL 2",
  "image 2": "Image URL 2",
  "image url 3": "Image URL 3",
  "image 3": "Image URL 3",
  "image url 4": "Image URL 4",
  "image 4": "Image URL 4",
};

function emptySpecRow(): Record<InventoryColumn, string | number> {
  return Object.fromEntries(INVENTORY_COLUMNS.map((c) => [c, ""])) as Record<InventoryColumn, string | number>;
}

/** Demo rows: ICE + EV — same shape dealers upload in real life. */
export const SAMPLE_ROWS: Record<InventoryColumn, string | number>[] = [
  {
    ...emptySpecRow(),
    Brand: "Hyundai",
    Model: "Creta",
    Variant: "SX(O) 1.5 Petrol",
    Year: 2025,
    Fuel: "Petrol",
    Transmission: "IVT",
    "Body Type": "SUV",
    "Engine CC": "1497",
    Mileage: "17.4 kmpl",
    Power: "113 bhp",
    Torque: "144 Nm",
    Seating: "5",
    "Boot Space": "433 litres",
    "Ground Clearance": "190 mm",
    "Drive Type": "FWD",
    Airbags: "6",
    "KM Driven": 0,
    Ownership: 0,
    Price: 1485000,
    "Ex-Showroom Price": 1485000,
    "On-Road Price": 1663000,
    Color: "Atlas White",
    Description: "Demo ICE — exact price + full real new-car specs",
    "Dealer Price": 1450000,
    "Waiting Period Days": 14,
    Features: "Sunroof|Ventilated seats|ADAS Level 2|Wireless Android Auto",
  },
  {
    ...emptySpecRow(),
    Brand: "Tata",
    Model: "Nexon EV",
    Variant: "Creative+ 45",
    Year: 2025,
    Fuel: "Electric",
    Transmission: "Automatic",
    "Body Type": "SUV",
    "Range Km": "489 km",
    "Battery kWh": "45",
    Power: "150 bhp",
    Torque: "215 Nm",
    Seating: "5",
    "Boot Space": "350 litres",
    "Ground Clearance": "205 mm",
    "Drive Type": "FWD",
    Airbags: "6",
    "KM Driven": 0,
    Ownership: 0,
    Price: 1499000,
    "Ex-Showroom Price": 1499000,
    "On-Road Price": 1685000,
    Color: "Daytona Grey",
    Description: "Demo EV — Range Km + Battery kWh (Engine CC blank)",
    "Dealer Price": 1475000,
    "Waiting Period Days": 21,
    Features: "Fast charger|Connected car|Sunroof|Auto park assist",
  },
  {
    ...emptySpecRow(),
    Brand: "MG",
    Model: "Windsor EV",
    Variant: "Essence",
    Year: 2025,
    Fuel: "Electric",
    Transmission: "Automatic",
    "Body Type": "SUV",
    "Range Km": "331 km",
    "Battery kWh": "38",
    Power: "134 bhp",
    Torque: "200 Nm",
    Seating: "5",
    "Boot Space": "604 litres",
    "Ground Clearance": "186 mm",
    "Drive Type": "FWD",
    Airbags: "6",
    "KM Driven": 0,
    Ownership: 0,
    Price: 1399000,
    "Ex-Showroom Price": 1399000,
    Color: "Pearl White",
    Description: "Demo EV — battery + range filled",
    "Dealer Price": 1375000,
    "Waiting Period Days": 28,
    Features: "iSMART|Panoramic glass roof|Vehicle-to-load",
  },
  {
    ...emptySpecRow(),
    Brand: "Mahindra",
    Model: "XUV700",
    Variant: "AX7 Diesel AT",
    Year: 2025,
    Fuel: "Diesel",
    Transmission: "Automatic",
    "Body Type": "SUV",
    "Engine CC": "2184",
    Mileage: "17 kmpl",
    Power: "182 bhp",
    Torque: "450 Nm",
    Seating: "7",
    "Boot Space": "540 litres",
    "Ground Clearance": "200 mm",
    "Drive Type": "AWD",
    Airbags: "7",
    "KM Driven": 0,
    Ownership: 0,
    Price: "Rs. 13.99 - 24.50 Lakh",
    "Ex-Showroom Price": "Rs. 13.99 - 24.50 Lakh",
    Color: "Napoli Black",
    Description: "Demo — price range = Price on request (no invented amount)",
    "Waiting Period Days": 21,
    Features: "Panoramic sunroof|AdrenoX|360 camera",
  },
  {
    ...emptySpecRow(),
    Brand: "Maruti Suzuki",
    Model: "Fronx",
    Variant: "Alpha",
    Year: 2026,
    Fuel: "Petrol",
    Transmission: "Manual",
    "Body Type": "Crossover",
    "Engine CC": "1197",
    Mileage: "21.79 kmpl",
    Power: "88 bhp",
    Torque: "113 Nm",
    Seating: "5",
    "Boot Space": "308 litres",
    "Ground Clearance": "190 mm",
    "Drive Type": "FWD",
    Airbags: "6",
    "KM Driven": 0,
    Ownership: 0,
    Color: "Splendid Silver",
    Description: "Demo — blank price = Price on request; add https image URLs when ready",
    "Waiting Period Days": 7,
    Features: "Head-up display|Cruise control",
  },
];

/** @deprecated use SAMPLE_ROWS */
export const SAMPLE_ROW = SAMPLE_ROWS[0]!;
