function envFlag(name: string, defaultOn = true): boolean {
  const v = process.env[name];
  if (v === undefined || v === "") return defaultOn;
  const lower = v.toLowerCase();
  return lower === "1" || lower === "true" || lower === "yes";
}

const ecosystemOn = envFlag("FEATURE_FULL_ECOSYSTEM", process.env.NODE_ENV === "production");

export const featureFlags = {
  vehicleSaleMode: envFlag("FEATURE_VEHICLE_SALE_MODE"),
  newCarInventoryV2: envFlag("FEATURE_NEW_CAR_INVENTORY_V2"),
  wishlistDb: envFlag("FEATURE_WISHLIST_DB"),
  unifiedVehicleApi: envFlag("FEATURE_UNIFIED_VEHICLE_API"),
  partsCompatibility: envFlag("FEATURE_PARTS_COMPATIBILITY"),
  auctionV2: envFlag("FEATURE_AUCTION_V2", ecosystemOn),
  auctionCategories: envFlag("FEATURE_AUCTION_CATEGORIES", ecosystemOn),
  auctionProxyBid: envFlag("FEATURE_AUCTION_PROXY_BID", ecosystemOn),
  auctionAutoBid: envFlag("FEATURE_AUCTION_AUTO_BID", ecosystemOn),
  auctionWatchlist: envFlag("FEATURE_AUCTION_WATCHLIST", ecosystemOn),
  auctionBidHistory: envFlag("FEATURE_AUCTION_BID_HISTORY", ecosystemOn),
  auctionKycGate: envFlag("FEATURE_AUCTION_KYC_GATE", ecosystemOn),
  brokerCrm: envFlag("FEATURE_BROKER_CRM", ecosystemOn),
  brokerContacts: envFlag("FEATURE_BROKER_CONTACTS", ecosystemOn),
  brokerLeads: envFlag("FEATURE_BROKER_LEADS", ecosystemOn),
  brokerDeals: envFlag("FEATURE_BROKER_DEALS", ecosystemOn),
  brokerVehicleAssign: envFlag("FEATURE_BROKER_VEHICLE_ASSIGN", ecosystemOn),
  brokerTasks: envFlag("FEATURE_BROKER_TASKS", ecosystemOn),
  brokerCommissions: envFlag("FEATURE_BROKER_COMMISSIONS", ecosystemOn),
  brokerWhatsapp: envFlag("FEATURE_BROKER_WHATSAPP", ecosystemOn),
  brokerMarketplaceBridge: envFlag("FEATURE_BROKER_MARKETPLACE_BRIDGE", ecosystemOn),
  communityV2: envFlag("FEATURE_COMMUNITY_V2", ecosystemOn),
  communityProfiles: envFlag("FEATURE_COMMUNITY_PROFILES", ecosystemOn),
  communityBusinessProfiles: envFlag("FEATURE_COMMUNITY_BUSINESS_PROFILES", ecosystemOn),
  communityFeed: envFlag("FEATURE_COMMUNITY_FEED", ecosystemOn),
  communityPosts: envFlag("FEATURE_COMMUNITY_POSTS", ecosystemOn),
  communityFollow: envFlag("FEATURE_COMMUNITY_FOLLOW", ecosystemOn),
  communityGroups: envFlag("FEATURE_COMMUNITY_GROUPS", ecosystemOn),
  communityGroupFeed: envFlag("FEATURE_COMMUNITY_GROUP_FEED", ecosystemOn),
  communityGroupModeration: envFlag("FEATURE_COMMUNITY_GROUP_MODERATION", ecosystemOn),
  communityBusinessPages: envFlag("FEATURE_COMMUNITY_BUSINESS_PAGES", ecosystemOn),
  growthV2: envFlag("FEATURE_GROWTH_V2", ecosystemOn),
  growthWorkspaces: envFlag("FEATURE_GROWTH_WORKSPACES", ecosystemOn),
  growthAssets: envFlag("FEATURE_GROWTH_ASSETS", ecosystemOn),
  growthPosters: envFlag("FEATURE_GROWTH_POSTERS", ecosystemOn),
  growthWhatsapp: envFlag("FEATURE_GROWTH_WHATSAPP", ecosystemOn),
  growthLeads: envFlag("FEATURE_GROWTH_LEADS", ecosystemOn),
  growthLeadPipeline: envFlag("FEATURE_GROWTH_LEAD_PIPELINE", ecosystemOn),
  businessDirectoryV2: envFlag("FEATURE_BUSINESS_DIRECTORY_V2", ecosystemOn),
  directoryMonetizationK1: envFlag("FEATURE_K1_DIRECTORY_MONETIZATION", ecosystemOn),
  growthWhatsappProviders: envFlag("FEATURE_GROWTH_WHATSAPP_PROVIDERS", ecosystemOn),
  growthSocialScheduler: envFlag("FEATURE_GROWTH_SOCIAL_SCHEDULER", ecosystemOn),
  founderDashboard: envFlag("FEATURE_M0_FOUNDER_DASHBOARD", ecosystemOn),
  unifiedIdentity: envFlag("FEATURE_M1_UNIFIED_IDENTITY", ecosystemOn),
  unifiedBusiness: envFlag("FEATURE_M2_UNIFIED_BUSINESS", ecosystemOn),
  leadRouter: envFlag("FEATURE_M3_LEAD_ROUTER", ecosystemOn),
  unifiedNotifications: envFlag("FEATURE_M4_NOTIFICATIONS", true),
  unifiedSearch: envFlag("FEATURE_M5_UNIFIED_SEARCH", true),
  billingV2: envFlag("FEATURE_BILLING_V2", ecosystemOn),
  /** Phase Catalog 1 — master catalog tables (default OFF until Phase 2+) */
  catalogLayer: envFlag("FEATURE_CATALOG_LAYER", false),
  catalogPublicApi: envFlag("FEATURE_CATALOG_PUBLIC_API", false),
  catalogAdmin: envFlag("FEATURE_CATALOG_ADMIN", false),
  /** Phase 3 organization / partner foundation */
  organizationLayer: envFlag("FEATURE_ORGANIZATION_LAYER", true),
  /** Phase C — finance marketplace REST (default on in dev; set false to keep RPC/mock) */
  financeMarketplace: envFlag("FEATURE_FINANCE_MARKETPLACE"),
  financeEligibilityApi: envFlag("FEATURE_FINANCE_ELIGIBILITY_API"),
  financeCompareApi: envFlag("FEATURE_FINANCE_COMPARE_API"),
  financeSoftApproval: envFlag("FEATURE_FINANCE_SOFT_APPROVAL"),
  financeDocumentsApi: envFlag("FEATURE_FINANCE_DOCUMENTS_API"),
  salesOs: envFlag("FEATURE_SALES_OS"),
  leadBoard: envFlag("FEATURE_LEAD_BOARD", false),
  paidLeads: envFlag("FEATURE_PAID_LEADS", false),
  commercialEngine: envFlag("FEATURE_COMMERCIAL_ENGINE"),
  paymentGateway: envFlag("FEATURE_PAYMENT_GATEWAY", false),
  communications: envFlag("FEATURE_COMMUNICATIONS", true),
  dialer: envFlag("FEATURE_DIALER", false),
  aiCalling: envFlag("FEATURE_AI_CALLING", false),
} as const;
