import type { PlanDefinition, PlanSlug } from "./types";

export const BILLING_PLANS: PlanDefinition[] = [
  {
    id: "plan_free",
    slug: "free",
    name: "Free",
    tier_rank: 0,
    price_monthly_inr: 0,
    price_annual_inr: 0,
    module_entitlements: {
      "marketplace.active_listings": 3,
      "community.posts_monthly": 10,
      "community.business_page": true,
      "growth.workspaces": 1,
      "growth.broadcasts_monthly": 20,
      "growth.lead_events_monthly": 50,
      "growth.storage_mb": 256,
      "growth.design_exports_monthly": 5,
      "growth.campaigns_active": 1,
      "auctions.entries_monthly": 0,
      "lead_router.ingress_monthly": 20,
      "entitlement.marketplace.publish": true,
      "entitlement.directory.monetization_k1": false,
      "entitlement.growth.whatsapp": true,
      "entitlement.auctions.participate": false,
    },
    business_type_overrides: {},
  },
  {
    id: "plan_starter",
    slug: "starter",
    name: "Starter",
    tier_rank: 1,
    price_monthly_inr: 999,
    price_annual_inr: 9990,
    module_entitlements: {
      "marketplace.active_listings": 15,
      "community.posts_monthly": 30,
      "community.business_page": true,
      "growth.workspaces": 1,
      "growth.broadcasts_monthly": 100,
      "growth.lead_events_monthly": 200,
      "growth.storage_mb": 512,
      "growth.design_exports_monthly": 25,
      "growth.campaigns_active": 3,
      "auctions.entries_monthly": 0,
      "lead_router.ingress_monthly": 100,
      "entitlement.marketplace.publish": true,
      "entitlement.directory.monetization_k1": false,
      "entitlement.growth.whatsapp": true,
      "entitlement.auctions.participate": false,
    },
    business_type_overrides: {
      workshop: { "marketplace.active_listings": 5 },
    },
  },
  {
    id: "plan_professional",
    slug: "professional",
    name: "Professional",
    tier_rank: 2,
    price_monthly_inr: 2999,
    price_annual_inr: 29990,
    module_entitlements: {
      "marketplace.active_listings": 50,
      "community.posts_monthly": 100,
      "community.business_page": true,
      "growth.workspaces": 1,
      "growth.broadcasts_monthly": 500,
      "growth.lead_events_monthly": 1000,
      "growth.storage_mb": 2048,
      "growth.design_exports_monthly": 100,
      "growth.campaigns_active": 10,
      "auctions.entries_monthly": 5,
      "lead_router.ingress_monthly": 500,
      "entitlement.marketplace.publish": true,
      "entitlement.directory.monetization_k1": true,
      "entitlement.growth.whatsapp": true,
      "entitlement.growth.social_scheduler": true,
      "entitlement.auctions.participate": true,
    },
    business_type_overrides: {
      broker: { "marketplace.active_listings": 10, "growth.lead_events_monthly": 1500 },
      dsa: { "growth.lead_events_monthly": 2000 },
    },
  },
  {
    id: "plan_business",
    slug: "business",
    name: "Business",
    tier_rank: 3,
    price_monthly_inr: 7999,
    price_annual_inr: 79990,
    module_entitlements: {
      "marketplace.active_listings": 150,
      "community.posts_monthly": 500,
      "community.business_page": true,
      "growth.workspaces": 3,
      "growth.broadcasts_monthly": 2000,
      "growth.lead_events_monthly": 5000,
      "growth.storage_mb": 10240,
      "growth.design_exports_monthly": 500,
      "growth.campaigns_active": 25,
      "auctions.entries_monthly": 25,
      "lead_router.ingress_monthly": 2000,
      "platform.team_seats": 10,
      "entitlement.marketplace.publish": true,
      "entitlement.directory.monetization_k1": true,
      "entitlement.growth.whatsapp": true,
      "entitlement.growth.social_scheduler": true,
      "entitlement.auctions.participate": true,
    },
    business_type_overrides: {
      dealer: { "auctions.entries_monthly": 40 },
    },
  },
  {
    id: "plan_enterprise",
    slug: "enterprise",
    name: "Enterprise",
    tier_rank: 4,
    price_monthly_inr: 25000,
    price_annual_inr: 250000,
    module_entitlements: {
      "marketplace.active_listings": 9999,
      "community.posts_monthly": 9999,
      "community.business_page": true,
      "growth.workspaces": 99,
      "growth.broadcasts_monthly": 99999,
      "growth.lead_events_monthly": 99999,
      "growth.storage_mb": 102400,
      "growth.design_exports_monthly": 9999,
      "growth.campaigns_active": 999,
      "auctions.entries_monthly": 999,
      "lead_router.ingress_monthly": 99999,
      "platform.team_seats": 99,
      "entitlement.marketplace.publish": true,
      "entitlement.directory.monetization_k1": true,
      "entitlement.growth.whatsapp": true,
      "entitlement.growth.social_scheduler": true,
      "entitlement.auctions.participate": true,
      "entitlement.ai.marketing": true,
    },
    business_type_overrides: {},
  },
];

export function getPlanBySlug(slug: string): PlanDefinition | null {
  return BILLING_PLANS.find((p) => p.slug === slug) ?? null;
}

export function getPlanSlugFromTierRank(rank: number): PlanSlug | null {
  const p = BILLING_PLANS.find((x) => x.tier_rank === rank);
  return p?.slug ?? null;
}
